master:
  securityRealm: |-
    <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
      <disableSignup>true</disableSignup>
      <enableCaptcha>false</enableCaptcha>
    </securityRealm>
  # Allows to configure different AuthorizationStrategy using Jenkins XML
  authorizationStrategy: |-
   
    <authorizationStrategy class="com.michelin.cio.hudson.plugins.rolestrategy.RoleBasedAuthorizationStrategy">
      <roleMap type="globalRoles">
        <role name="admin" pattern=".*">
          <permissions>
            <permission>hudson.model.View.Delete</permission>
            <permission>hudson.model.Computer.Connect</permission>
            <permission>hudson.model.Run.Delete</permission>
            <permission>com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains</permission>
            <permission>hudson.model.Computer.Create</permission>
            <permission>hudson.model.View.Configure</permission>
            <permission>hudson.model.Computer.Build</permission>
            <permission>hudson.model.Item.Configure</permission>
            <permission>hudson.model.Hudson.Administer</permission>
            <permission>hudson.model.Item.Cancel</permission>
            <permission>hudson.model.Item.Read</permission>
            <permission>com.cloudbees.plugins.credentials.CredentialsProvider.View</permission>
            <permission>hudson.model.Computer.Delete</permission>
            <permission>hudson.model.Item.Build</permission>
            <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.Unlock</permission>
            <permission>hudson.model.Item.ExtendedRead</permission>
            <permission>hudson.scm.SCM.Tag</permission>
            <permission>hudson.model.Item.Move</permission>
            <permission>hudson.model.Item.Discover</permission>
            <permission>hudson.model.Hudson.Read</permission>
            <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Update</permission>
            <permission>hudson.model.Item.Create</permission>
            <permission>hudson.model.Item.Workspace</permission>
            <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Delete</permission>
            <permission>hudson.model.Computer.Provision</permission>
            <permission>hudson.model.Run.Replay</permission>
            <permission>hudson.model.View.Read</permission>
            <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.View</permission>
            <permission>hudson.model.Hudson.SystemRead</permission>
            <permission>hudson.model.View.Create</permission>
            <permission>hudson.model.Computer.ExtendedRead</permission>
            <permission>hudson.model.Item.Delete</permission>
            <permission>hudson.model.Computer.Configure</permission>
            <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Create</permission>
            <permission>hudson.model.Computer.Disconnect</permission>
            <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.Reserve</permission>
            <permission>hudson.model.Run.Update</permission>
          </permissions>
          <assignedSIDs>
            <sid>salil</sid>
          </assignedSIDs>
        </role>
        <role name="trg-client" pattern="trg.*">
          <permissions>
            <permission>hudson.model.Hudson.Read</permission>
            <permission>hudson.model.Item.Read</permission>
            <permission>hudson.model.Item.Create</permission>
            <permission>hudson.model.Item.Workspace</permission>
            <permission>hudson.model.Item.Build</permission>
            <permission>hudson.model.Item.ExtendedRead</permission>
            <permission>hudson.model.Item.Configure</permission>
            <permission>hudson.model.Item.Discover</permission>
          </permissions>
        </role>
      </roleMap>
      <roleMap type="slaveRoles"/>
      <roleMap type="projectRoles"/>
    </authorizationStrategy>